version: '3'
services:
  sparrow-api:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT: "8080"
      - APP_VERSION: "0.1.0"
    ports:
      - "8080:8080"
